pub struct Test.TestRunner {
  use Zest.Runner

  pub fn main(_args :: [String]) -> String {
    Test.HelloWorldTest.run()
    Test.PatternMatchingTest.run()
    Test.PipesTest.run()
    Test.CaseExpressionTest.run()
    Test.StringTest.run()
    Test.ArithmeticTest.run()
    Test.BooleanTest.run()
    Test.AtomTest.run()
    Test.FunctionTest.run()
    Test.MacroTest.run()
    Test.RecursionTest.run()
    Test.GuardTest.run()
    Test.MultiStructTest.run()
    Test.ImportTest.run()
    Test.UnionTest.run()
    Test.CondTest.run()
    Test.MultiArityTest.run()
    Test.IfElseTest.run()
    Test.TupleTest.run()
    Test.DefaultParamsTest.run()
    Test.CatchBasinTest.run()
    Test.ForComprehensionTest.run()
    Test.ClosureTest.run()
    Test.ZestFeaturesTest.run()
    Test.BinaryPatternTest.run()
    Test.IntegerTest.run()
    Test.FloatTest.run()
    Test.BoolTest.run()
    Test.ListTest.run()
    Test.EnumTest.run()
    Test.MapTest.run()
    Test.FileTest.run()
    Test.MathTest.run()
    Test.ProtocolTest.run()
    Test.StructTest.run()
    Test.RangeTest.run()
    Test.OperatorNameTest.run()
    Zest.Runner.run()
  }
}
