const std = @import("std");
const ir = @import("ir.zig");
const ast = @import("ast.zig");
const types_mod = @import("types.zig");

// ============================================================
// Zig source code generator (spec §22.1)
//
// Emits canonical Zig source from the Zig-shaped IR.
// Stage 1: plain Zig source for correctness and debugging.
// ============================================================

pub const CodeGen = struct {
    allocator: std.mem.Allocator,
    output: std.ArrayList(u8),
    indent_level: u32,
    referenced_locals: std.ArrayListUnmanaged(ir.LocalId),
    current_fn_is_void: bool,
    current_fn_params: []const ir.Param,
    next_block_label: u32,
    current_case_label: ?[]const u8,
    lib_mode: bool,

    pub fn init(allocator: std.mem.Allocator) CodeGen {
        return .{
            .allocator = allocator,
            .output = .empty,
            .indent_level = 0,
            .referenced_locals = .empty,
            .current_fn_is_void = false,
            .current_fn_params = &.{},
            .next_block_label = 0,
            .current_case_label = null,
            .lib_mode = false,
        };
    }

    pub fn deinit(self: *CodeGen) void {
        self.output.deinit(self.allocator);
        self.referenced_locals.deinit(self.allocator);
    }

    pub fn getOutput(self: *const CodeGen) []const u8 {
        return self.output.items;
    }

    // ============================================================
    // Program emission
    // ============================================================

    pub fn emitProgram(self: *CodeGen, program: *const ir.Program) !void {
        // File header
        try self.write("// Generated by Zap compiler\n");
        try self.write("const std = @import(\"std\");\n");
        try self.write("const zap_runtime = @import(\"zap_runtime.zig\");\n");
        try self.write("\n");

        for (program.functions) |func| {
            try self.emitFunction(&func);
            try self.write("\n");
        }
    }

    // ============================================================
    // Function emission
    // ============================================================

    fn emitFunction(self: *CodeGen, func: *const ir.Function) !void {
        const is_main = std.mem.eql(u8, func.name, "main");

        // In library mode, skip main and make all other functions pub
        if (self.lib_mode and is_main) return;

        // Function signature — pub for main (exe) or all functions (lib)
        if (is_main or self.lib_mode) {
            try self.write("pub fn ");
        } else {
            try self.write("fn ");
        }
        try self.write(func.name);
        try self.write("(");

        for (func.params, 0..) |param, i| {
            if (i > 0) try self.write(", ");
            try self.write(param.name);
            try self.write(": ");
            try self.emitZigType(&param.type_expr);
        }

        try self.write(") ");
        // Zig entry point must return void, !void, noreturn, u8, or !u8
        if (is_main) {
            try self.write("void");
        } else {
            try self.emitZigType(&func.return_type);
        }
        self.current_fn_is_void = is_main or func.return_type == .void;
        self.current_fn_params = func.params;
        try self.write(" {\n");
        self.indent_level += 1;

        // Suppress unused parameter errors in generated Zig.
        // Only discard params that are truly unreferenced in the body.
        for (func.params, 0..) |param, param_idx| {
            var used = false;
            for (func.body) |block| {
                if (self.isParamUsedInInstrs(block.instructions, @intCast(param_idx))) {
                    used = true;
                    break;
                }
            }
            if (!used) {
                try self.writeIndent();
                try self.write("_ = ");
                try self.write(param.name);
                try self.write(";\n");
            }
        }

        // Emit body blocks
        for (func.body) |block| {
            try self.emitBlock(&block);
        }

        self.indent_level -= 1;
        try self.write("}\n");
    }

    fn emitBlock(self: *CodeGen, block: *const ir.Block) !void {
        // Collect which locals are referenced as sources
        self.referenced_locals = .empty;
        for (block.instructions) |instr| {
            self.collectReferencedLocals(&instr);
        }

        for (block.instructions) |instr| {
            try self.emitInstruction(&instr);
        }
    }

    fn isLocalReferenced(self: *const CodeGen, id: ir.LocalId) bool {
        for (self.referenced_locals.items) |ref_id| {
            if (ref_id == id) return true;
        }
        return false;
    }

    fn collectReferencedLocals(self: *CodeGen, instr: *const ir.Instruction) void {
        switch (instr.*) {
            .local_get => |lg| self.referenced_locals.append(self.allocator, lg.source) catch {},
            .local_set => |ls| self.referenced_locals.append(self.allocator, ls.value) catch {},
            .binary_op => |bo| {
                self.referenced_locals.append(self.allocator, bo.lhs) catch {};
                self.referenced_locals.append(self.allocator, bo.rhs) catch {};
            },
            .unary_op => |uo| {
                self.referenced_locals.append(self.allocator, uo.operand) catch {};
            },
            .call_direct => |cd| {
                for (cd.args) |arg| self.referenced_locals.append(self.allocator, arg) catch {};
            },
            .call_named => |cn| {
                for (cn.args) |arg| self.referenced_locals.append(self.allocator, arg) catch {};
            },
            .call_closure => |cc| {
                self.referenced_locals.append(self.allocator, cc.callee) catch {};
                for (cc.args) |arg| self.referenced_locals.append(self.allocator, arg) catch {};
            },
            .call_dispatch => |cd_disp| {
                for (cd_disp.args) |arg| self.referenced_locals.append(self.allocator, arg) catch {};
            },
            .call_builtin => |cb| {
                for (cb.args) |arg| self.referenced_locals.append(self.allocator, arg) catch {};
            },
            .match_atom => |ma| self.referenced_locals.append(self.allocator, ma.scrutinee) catch {},
            .match_int => |mi| self.referenced_locals.append(self.allocator, mi.scrutinee) catch {},
            .match_float => |mf| self.referenced_locals.append(self.allocator, mf.scrutinee) catch {},
            .match_string => |ms| self.referenced_locals.append(self.allocator, ms.scrutinee) catch {},
            .match_type => |mt| self.referenced_locals.append(self.allocator, mt.scrutinee) catch {},
            .cond_branch => |cb| self.referenced_locals.append(self.allocator, cb.condition) catch {},
            .cond_return => |cr| {
                self.referenced_locals.append(self.allocator, cr.condition) catch {};
                if (!self.current_fn_is_void) {
                    if (cr.value) |v| self.referenced_locals.append(self.allocator, v) catch {};
                }
            },
            .ret => |r| {
                if (!self.current_fn_is_void) {
                    if (r.value) |v| self.referenced_locals.append(self.allocator, v) catch {};
                }
            },
            .tuple_init => |ti| {
                for (ti.elements) |elem| self.referenced_locals.append(self.allocator, elem) catch {};
            },
            .list_init => |li| {
                for (li.elements) |elem| self.referenced_locals.append(self.allocator, elem) catch {};
            },
            .make_closure => |mc| {
                for (mc.captures) |cap| self.referenced_locals.append(self.allocator, cap) catch {};
            },
            .if_expr => |ie| {
                self.referenced_locals.append(self.allocator, ie.condition) catch {};
                for (ie.then_instrs) |sub_instr| {
                    self.collectReferencedLocals(&sub_instr);
                }
                for (ie.else_instrs) |sub_instr| {
                    self.collectReferencedLocals(&sub_instr);
                }
                if (ie.then_result) |tr| self.referenced_locals.append(self.allocator, tr) catch {};
                if (ie.else_result) |er| self.referenced_locals.append(self.allocator, er) catch {};
            },
            .guard_block => |gb| {
                self.referenced_locals.append(self.allocator, gb.condition) catch {};
                for (gb.body) |sub_instr| {
                    self.collectReferencedLocals(&sub_instr);
                }
            },
            .case_block => |cb| {
                for (cb.pre_instrs) |sub_instr| self.collectReferencedLocals(&sub_instr);
                for (cb.arms) |arm| {
                    for (arm.cond_instrs) |sub_instr| self.collectReferencedLocals(&sub_instr);
                    self.referenced_locals.append(self.allocator, arm.condition) catch {};
                    for (arm.body_instrs) |sub_instr| self.collectReferencedLocals(&sub_instr);
                    if (arm.result) |r| self.referenced_locals.append(self.allocator, r) catch {};
                }
                for (cb.default_instrs) |sub_instr| self.collectReferencedLocals(&sub_instr);
                if (cb.default_result) |r| self.referenced_locals.append(self.allocator, r) catch {};
            },
            .case_break => |cbr| {
                if (cbr.value) |v| self.referenced_locals.append(self.allocator, v) catch {};
            },
            .index_get => |ig| {
                self.referenced_locals.append(self.allocator, ig.object) catch {};
            },
            else => {},
        }
    }

    fn isParamUsedInInstrs(self: *const CodeGen, instrs: []const ir.Instruction, param_idx: u32) bool {
        for (instrs) |instr| {
            switch (instr) {
                .param_get => |pg| {
                    if (pg.index == param_idx) return true;
                },
                .if_expr => |ie| {
                    if (self.isParamUsedInInstrs(ie.then_instrs, param_idx)) return true;
                    if (self.isParamUsedInInstrs(ie.else_instrs, param_idx)) return true;
                },
                .guard_block => |gb| {
                    if (self.isParamUsedInInstrs(gb.body, param_idx)) return true;
                },
                .case_block => |cb| {
                    if (self.isParamUsedInInstrs(cb.pre_instrs, param_idx)) return true;
                    for (cb.arms) |arm| {
                        if (self.isParamUsedInInstrs(arm.cond_instrs, param_idx)) return true;
                        if (self.isParamUsedInInstrs(arm.body_instrs, param_idx)) return true;
                    }
                    if (self.isParamUsedInInstrs(cb.default_instrs, param_idx)) return true;
                },
                else => {},
            }
        }
        return false;
    }

    // ============================================================
    // Instruction emission
    // ============================================================

    fn emitInstruction(self: *CodeGen, instr: *const ir.Instruction) !void {
        switch (instr.*) {
            .const_int => |ci| {
                try self.writeIndent();
                try self.writeDestLocal(ci.dest);
                try self.write(" = ");
                try self.writeInt(ci.value);
                try self.write(";\n");
            },
            .const_float => |cf| {
                try self.writeIndent();
                try self.writeDestLocal(cf.dest);
                try self.write(" = ");
                try self.writeFloat(cf.value);
                try self.write(";\n");
            },
            .const_string => |cs| {
                try self.writeIndent();
                try self.writeDestLocal(cs.dest);
                try self.write(" = \"");
                try self.write(cs.value);
                try self.write("\";\n");
            },
            .const_bool => |cb| {
                try self.writeIndent();
                try self.writeDestLocal(cb.dest);
                try self.write(if (cb.value) " = true;\n" else " = false;\n");
            },
            .const_atom => |ca| {
                try self.writeIndent();
                try self.writeDestLocal(ca.dest);
                try self.write(" = .@\"");
                try self.write(ca.value);
                try self.write("\";\n");
            },
            .const_nil => |dest| {
                try self.writeIndent();
                try self.writeDestLocal(dest);
                try self.write(" = null;\n");
            },
            .local_get => |lg| {
                try self.writeIndent();
                try self.writeDestLocal(lg.dest);
                try self.write(" = ");
                try self.writeLocal(lg.source);
                try self.write(";\n");
            },
            .local_set => |ls| {
                try self.writeIndent();
                try self.writeDestLocal(ls.dest);
                try self.write(" = ");
                try self.writeLocal(ls.value);
                try self.write(";\n");
            },
            .param_get => |pg| {
                try self.writeIndent();
                try self.writeDestLocal(pg.dest);
                try self.write(" = ");
                try self.writeParam(pg.index);
                try self.write(";\n");
            },
            .binary_op => |bo| {
                if (bo.op == .concat) {
                    // String concat uses runtime allocator
                    try self.writeIndent();
                    try self.writeDestLocal(bo.dest);
                    try self.write(" = zap_runtime.ZapString.concat(std.heap.page_allocator, ");
                    try self.writeLocal(bo.lhs);
                    try self.write(", ");
                    try self.writeLocal(bo.rhs);
                    try self.write(") catch \"\";\n");
                } else {
                    try self.writeIndent();
                    try self.writeDestLocal(bo.dest);
                    try self.write(" = ");
                    try self.writeLocal(bo.lhs);
                    try self.write(switch (bo.op) {
                        .add => " + ",
                        .sub => " - ",
                        .mul => " * ",
                        .div => " / ",
                        .rem_op => " % ",
                        .eq => " == ",
                        .neq => " != ",
                        .lt => " < ",
                        .gt => " > ",
                        .lte => " <= ",
                        .gte => " >= ",
                        .bool_and => " and ",
                        .bool_or => " or ",
                        .concat => unreachable,
                    });
                    try self.writeLocal(bo.rhs);
                    try self.write(";\n");
                }
            },
            .unary_op => |uo| {
                try self.writeIndent();
                try self.writeDestLocal(uo.dest);
                try self.write(switch (uo.op) {
                    .negate => " = -",
                    .bool_not => " = !",
                });
                try self.writeLocal(uo.operand);
                try self.write(";\n");
            },
            .call_direct => |cd| {
                try self.writeIndent();
                try self.writeDestLocal(cd.dest);
                try self.write(" = func_");
                try self.writeInt(@intCast(cd.function));
                try self.write("(");
                for (cd.args, 0..) |arg, i| {
                    if (i > 0) try self.write(", ");
                    try self.writeLocal(arg);
                }
                try self.write(");\n");
            },
            .call_named => |cn| {
                try self.writeIndent();
                try self.writeDestLocal(cn.dest);
                try self.write(" = ");
                try self.write(cn.name);
                try self.write("(");
                for (cn.args, 0..) |arg, i| {
                    if (i > 0) try self.write(", ");
                    try self.writeLocal(arg);
                }
                try self.write(");\n");
            },
            .call_closure => |cc| {
                try self.writeIndent();
                try self.writeDestLocal(cc.dest);
                try self.write(" = ");
                try self.writeLocal(cc.callee);
                try self.write("(");
                for (cc.args, 0..) |arg, i| {
                    if (i > 0) try self.write(", ");
                    try self.writeLocal(arg);
                }
                try self.write(");\n");
            },
            .call_dispatch => |cd_disp| {
                try self.writeIndent();
                try self.writeDestLocal(cd_disp.dest);
                try self.write(" = dispatch_");
                try self.writeInt(@intCast(cd_disp.group_id));
                try self.write("(");
                for (cd_disp.args, 0..) |arg, i| {
                    if (i > 0) try self.write(", ");
                    try self.writeLocal(arg);
                }
                try self.write(");\n");
            },
            .match_atom => |ma| {
                // Type-safe atom comparison for anytype params
                try self.writeIndent();
                try self.writeDestLocal(ma.dest);
                try self.write(" = @TypeOf(");
                try self.writeLocal(ma.scrutinee);
                try self.write(") == @TypeOf(.@\"");
                try self.write(ma.atom_name);
                try self.write("\") and ");
                try self.writeLocal(ma.scrutinee);
                try self.write(" == .@\"");
                try self.write(ma.atom_name);
                try self.write("\";\n");
            },
            .match_int => |mi| {
                // Type-safe integer comparison for anytype params
                try self.writeIndent();
                try self.writeDestLocal(mi.dest);
                try self.write(" = (@typeInfo(@TypeOf(");
                try self.writeLocal(mi.scrutinee);
                try self.write(")) == .int or @typeInfo(@TypeOf(");
                try self.writeLocal(mi.scrutinee);
                try self.write(")) == .comptime_int) and ");
                try self.writeLocal(mi.scrutinee);
                try self.write(" == ");
                try self.writeInt(mi.value);
                try self.write(";\n");
            },
            .match_float => |mf| {
                // Type-safe float comparison for anytype params
                try self.writeIndent();
                try self.writeDestLocal(mf.dest);
                try self.write(" = (@typeInfo(@TypeOf(");
                try self.writeLocal(mf.scrutinee);
                try self.write(")) == .float or @typeInfo(@TypeOf(");
                try self.writeLocal(mf.scrutinee);
                try self.write(")) == .comptime_float) and ");
                try self.writeLocal(mf.scrutinee);
                try self.write(" == ");
                try self.writeFloat(mf.value);
                try self.write(";\n");
            },
            .match_string => |ms| {
                // Type-safe string comparison using std.mem.eql
                try self.writeIndent();
                try self.writeDestLocal(ms.dest);
                try self.write(" = @TypeOf(");
                try self.writeLocal(ms.scrutinee);
                try self.write(") == []const u8 and std.mem.eql(u8, ");
                try self.writeLocal(ms.scrutinee);
                try self.write(", \"");
                try self.write(ms.expected);
                try self.write("\");\n");
            },
            .match_type => |mt| {
                // Type guard for anytype params: @TypeOf(x) == expected
                // For integer/float types, also accept comptime_int/comptime_float
                // so that literal arguments (e.g. describe(20)) match properly.
                const needs_comptime_check = switch (mt.expected_type) {
                    .i8, .i16, .i32, .i64, .u8, .u16, .u32, .u64, .isize, .usize => true,
                    .f16, .f32, .f64 => true,
                    else => false,
                };
                const is_struct_check = mt.expected_type == .tuple;
                try self.writeIndent();
                try self.writeDestLocal(mt.dest);
                if (is_struct_check) {
                    // Tuple/struct type check: @typeInfo(@TypeOf(x)) == .@"struct"
                    try self.write(" = @typeInfo(@TypeOf(");
                    try self.writeLocal(mt.scrutinee);
                    try self.write(")) == .@\"struct\";\n");
                } else {
                    try self.write(" = @TypeOf(");
                    try self.writeLocal(mt.scrutinee);
                    try self.write(") == ");
                    try self.emitZigType(&mt.expected_type);
                    if (needs_comptime_check) {
                        const is_float = switch (mt.expected_type) {
                            .f16, .f32, .f64 => true,
                            else => false,
                        };
                        try self.write(" or @typeInfo(@TypeOf(");
                        try self.writeLocal(mt.scrutinee);
                        if (is_float) {
                            try self.write(")) == .comptime_float");
                        } else {
                            try self.write(")) == .comptime_int");
                        }
                    }
                    try self.write(";\n");
                }
            },
            .index_get => |ig| {
                try self.writeIndent();
                try self.writeDestLocal(ig.dest);
                try self.write(" = ");
                try self.writeLocal(ig.object);
                try self.write("[");
                try self.writeInt(@intCast(ig.index));
                try self.write("];\n");
            },
            .guard_block => |gb| {
                try self.writeIndent();
                try self.write("if (");
                try self.writeLocal(gb.condition);
                try self.write(") {\n");
                self.indent_level += 1;
                for (gb.body) |sub_instr| {
                    try self.emitInstruction(&sub_instr);
                }
                self.indent_level -= 1;
                try self.writeIndent();
                try self.write("}\n");
            },
            .case_block => |cb| {
                const block_label = self.next_block_label;
                self.next_block_label += 1;
                const label_str = try std.fmt.allocPrint(self.allocator, "blk_case_{d}", .{block_label});

                const saved_case_label = self.current_case_label;
                self.current_case_label = label_str;

                // const __local_N = blk_case_L: { ... };
                try self.writeIndent();
                try self.writeDestLocal(cb.dest);
                try self.write(" = ");
                try self.write(label_str);
                try self.write(": {\n");
                self.indent_level += 1;

                // Emit pre-instructions (tuple arm guards with case_break)
                for (cb.pre_instrs) |sub_instr| {
                    try self.emitInstruction(&sub_instr);
                }

                // Emit each conditional arm
                for (cb.arms) |arm| {
                    for (arm.cond_instrs) |sub_instr| {
                        try self.emitInstruction(&sub_instr);
                    }
                    try self.writeIndent();
                    try self.write("if (");
                    try self.writeLocal(arm.condition);
                    try self.write(") {\n");
                    self.indent_level += 1;
                    for (arm.body_instrs) |sub_instr| {
                        try self.emitInstruction(&sub_instr);
                    }
                    if (arm.result) |r| {
                        try self.writeIndent();
                        try self.write("break :");
                        try self.write(label_str);
                        try self.write(" ");
                        try self.writeLocal(r);
                        try self.write(";\n");
                    }
                    self.indent_level -= 1;
                    try self.writeIndent();
                    try self.write("}\n");
                }

                // Default arm
                for (cb.default_instrs) |sub_instr| {
                    try self.emitInstruction(&sub_instr);
                }
                if (cb.default_result) |r| {
                    try self.writeIndent();
                    try self.write("break :");
                    try self.write(label_str);
                    try self.write(" ");
                    try self.writeLocal(r);
                    try self.write(";\n");
                }

                self.indent_level -= 1;
                try self.writeIndent();
                try self.write("};\n");

                self.current_case_label = saved_case_label;
            },
            .case_break => |cbr| {
                if (self.current_case_label) |label| {
                    try self.writeIndent();
                    try self.write("break :");
                    try self.write(label);
                    if (cbr.value) |v| {
                        try self.write(" ");
                        try self.writeLocal(v);
                    }
                    try self.write(";\n");
                }
            },
            .if_expr => |ie| {
                const then_label = self.next_block_label;
                self.next_block_label += 1;
                const else_label = self.next_block_label;
                self.next_block_label += 1;

                // const __local_N = if (__local_C) blk_t_L: { ... } else blk_e_L: { ... };
                try self.writeIndent();
                try self.writeDestLocal(ie.dest);
                try self.write(" = if (");
                try self.writeLocal(ie.condition);
                try self.write(") ");

                // Then block
                const then_label_str = try std.fmt.allocPrint(self.allocator, "blk_t_{d}", .{then_label});
                try self.write(then_label_str);
                try self.write(": {\n");
                self.indent_level += 1;
                for (ie.then_instrs) |sub_instr| {
                    try self.emitInstruction(&sub_instr);
                }
                if (ie.then_result) |tr| {
                    try self.writeIndent();
                    try self.write("break :");
                    try self.write(then_label_str);
                    try self.write(" ");
                    try self.writeLocal(tr);
                    try self.write(";\n");
                }
                self.indent_level -= 1;
                try self.writeIndent();
                try self.write("} else ");

                // Else block
                const else_label_str = try std.fmt.allocPrint(self.allocator, "blk_e_{d}", .{else_label});
                try self.write(else_label_str);
                try self.write(": {\n");
                self.indent_level += 1;
                for (ie.else_instrs) |sub_instr| {
                    try self.emitInstruction(&sub_instr);
                }
                if (ie.else_result) |er| {
                    try self.writeIndent();
                    try self.write("break :");
                    try self.write(else_label_str);
                    try self.write(" ");
                    try self.writeLocal(er);
                    try self.write(";\n");
                }
                self.indent_level -= 1;
                try self.writeIndent();
                try self.write("};\n");
            },
            .cond_branch => |cb| {
                // TODO: proper block-based control flow
                try self.writeIndent();
                try self.write("_ = ");
                try self.writeLocal(cb.condition);
                try self.write("; // branch\n");
            },
            .cond_return => |cr| {
                try self.writeIndent();
                try self.write("if (");
                try self.writeLocal(cr.condition);
                try self.write(") return");
                if (!self.current_fn_is_void) {
                    if (cr.value) |v| {
                        try self.write(" ");
                        try self.writeLocal(v);
                    }
                }
                try self.write(";\n");
            },
            .branch => |br| {
                try self.writeIndent();
                try self.write("// goto label_");
                try self.writeInt(@intCast(br.target));
                try self.write("\n");
            },
            .ret => |r| {
                try self.writeIndent();
                try self.write("return");
                if (!self.current_fn_is_void) {
                    if (r.value) |v| {
                        try self.write(" ");
                        try self.writeLocal(v);
                    }
                }
                try self.write(";\n");
            },
            .tuple_init => |ti| {
                try self.writeIndent();
                try self.writeDestLocal(ti.dest);
                try self.write(" = .{");
                for (ti.elements, 0..) |elem, i| {
                    if (i > 0) try self.write(", ");
                    try self.writeLocal(elem);
                }
                try self.write("};\n");
            },
            .list_init => |li| {
                try self.writeIndent();
                try self.writeDestLocal(li.dest);
                try self.write(" = &.{");
                for (li.elements, 0..) |elem, i| {
                    if (i > 0) try self.write(", ");
                    try self.writeLocal(elem);
                }
                try self.write("};\n");
            },
            .match_fail => |mf| {
                try self.writeIndent();
                try self.write("@panic(\"");
                try self.write(mf.message);
                try self.write("\");\n");
            },
            .make_closure => |mc| {
                try self.writeIndent();
                try self.writeDestLocal(mc.dest);
                try self.write(" = makeClosure(func_");
                try self.writeInt(@intCast(mc.function));
                try self.write(", .{");
                for (mc.captures, 0..) |cap, i| {
                    if (i > 0) try self.write(", ");
                    try self.writeLocal(cap);
                }
                try self.write("});\n");
            },
            .call_builtin => |cb| {
                try self.writeIndent();
                try self.writeDestLocal(cb.dest);
                try self.write(" = zap_runtime.Prelude.");
                try self.write(cb.name);
                try self.write("(");
                for (cb.args, 0..) |arg, i| {
                    if (i > 0) try self.write(", ");
                    try self.writeLocal(arg);
                }
                try self.write(");\n");
            },
            else => {
                try self.writeIndent();
                try self.write("// unhandled instruction\n");
            },
        }
    }

    // ============================================================
    // Type emission
    // ============================================================

    fn emitZigType(self: *CodeGen, zig_type: *const ir.ZigType) !void {
        switch (zig_type.*) {
            .void => try self.write("void"),
            .bool_type => try self.write("bool"),
            .i8 => try self.write("i8"),
            .i16 => try self.write("i16"),
            .i32 => try self.write("i32"),
            .i64 => try self.write("i64"),
            .u8 => try self.write("u8"),
            .u16 => try self.write("u16"),
            .u32 => try self.write("u32"),
            .u64 => try self.write("u64"),
            .f16 => try self.write("f16"),
            .f32 => try self.write("f32"),
            .f64 => try self.write("f64"),
            .usize => try self.write("usize"),
            .isize => try self.write("isize"),
            .string => try self.write("[]const u8"),
            .atom => try self.write("zap_runtime.Atom"),
            .nil => try self.write("?void"),
            .any => try self.write("anytype"),
            .struct_ref => |name| try self.write(name),
            .tagged_union => |name| try self.write(name),
            else => try self.write("anytype"),
        }
    }

    // ============================================================
    // Write helpers
    // ============================================================

    fn write(self: *CodeGen, text: []const u8) !void {
        try self.output.appendSlice(self.allocator, text);
    }

    fn writeIndent(self: *CodeGen) !void {
        var i: u32 = 0;
        while (i < self.indent_level) : (i += 1) {
            try self.write("    ");
        }
    }

    fn writeLocal(self: *CodeGen, id: ir.LocalId) !void {
        const str = try std.fmt.allocPrint(self.allocator, "__local_{d}", .{id});
        try self.write(str);
    }

    fn writeDestLocal(self: *CodeGen, id: ir.LocalId) !void {
        if (self.isLocalReferenced(id)) {
            const str = try std.fmt.allocPrint(self.allocator, "const __local_{d}", .{id});
            try self.write(str);
        } else {
            try self.write("_");
        }
    }

    fn writeParam(self: *CodeGen, idx: u32) !void {
        if (idx < self.current_fn_params.len) {
            try self.write(self.current_fn_params[idx].name);
        } else {
            const str = try std.fmt.allocPrint(self.allocator, "__param_{d}", .{idx});
            try self.write(str);
        }
    }

    fn writeInt(self: *CodeGen, value: i64) !void {
        const str = try std.fmt.allocPrint(self.allocator, "{d}", .{value});
        try self.write(str);
    }

    fn writeFloat(self: *CodeGen, value: f64) !void {
        const str = try std.fmt.allocPrint(self.allocator, "{d}", .{value});
        try self.write(str);
    }
};

// ============================================================
// Tests
// ============================================================

const Parser = @import("parser.zig").Parser;
const Collector = @import("collector.zig").Collector;
const hir_mod = @import("hir.zig");

test "codegen simple function" {
    const source =
        \\def add(x :: i64, y :: i64) :: i64 do
        \\  x + y
        \\end
    ;

    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var parser = Parser.init(alloc, source);
    defer parser.deinit();
    const program = try parser.parseProgram();

    var collector = Collector.init(alloc, &parser.interner);
    defer collector.deinit();
    try collector.collectProgram(&program);

    var type_store = types_mod.TypeStore.init(alloc, &parser.interner);
    defer type_store.deinit();

    var hir_builder = hir_mod.HirBuilder.init(alloc, &parser.interner, &collector.graph, &type_store);
    defer hir_builder.deinit();
    const hir_program = try hir_builder.buildProgram(&program);

    var ir_builder = ir.IrBuilder.init(alloc, &parser.interner);
    defer ir_builder.deinit();
    const ir_program = try ir_builder.buildProgram(&hir_program);

    var codegen = CodeGen.init(alloc);
    defer codegen.deinit();
    try codegen.emitProgram(&ir_program);

    const output = codegen.getOutput();
    // Should contain function definition
    try std.testing.expect(std.mem.indexOf(u8, output, "fn add") != null);
    // Should contain return statement
    try std.testing.expect(std.mem.indexOf(u8, output, "return") != null);
}

test "codegen produces valid structure" {
    const source =
        \\def foo() do
        \\  42
        \\end
    ;

    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var parser = Parser.init(alloc, source);
    defer parser.deinit();
    const program = try parser.parseProgram();

    var collector = Collector.init(alloc, &parser.interner);
    defer collector.deinit();
    try collector.collectProgram(&program);

    var type_store = types_mod.TypeStore.init(alloc, &parser.interner);
    defer type_store.deinit();

    var hir_builder = hir_mod.HirBuilder.init(alloc, &parser.interner, &collector.graph, &type_store);
    defer hir_builder.deinit();
    const hir_program = try hir_builder.buildProgram(&program);

    var ir_builder = ir.IrBuilder.init(alloc, &parser.interner);
    defer ir_builder.deinit();
    const ir_program = try ir_builder.buildProgram(&hir_program);

    var codegen = CodeGen.init(alloc);
    defer codegen.deinit();
    try codegen.emitProgram(&ir_program);

    const output = codegen.getOutput();
    // Should contain header
    try std.testing.expect(std.mem.indexOf(u8, output, "Generated by Zap compiler") != null);
    // Should contain the literal 42
    try std.testing.expect(std.mem.indexOf(u8, output, "42") != null);
}
