const std = @import("std");
const ir = @import("ir.zig");
const ast = @import("ast.zig");
const types_mod = @import("types.zig");

// ============================================================
// Zig source code generator (spec §22.1)
//
// Emits canonical Zig source from the Zig-shaped IR.
// Stage 1: plain Zig source for correctness and debugging.
// ============================================================

pub const CodeGen = struct {
    allocator: std.mem.Allocator,
    output: std.ArrayList(u8),
    indent_level: u32,

    pub fn init(allocator: std.mem.Allocator) CodeGen {
        return .{
            .allocator = allocator,
            .output = .empty,
            .indent_level = 0,
        };
    }

    pub fn deinit(self: *CodeGen) void {
        self.output.deinit(self.allocator);
    }

    pub fn getOutput(self: *const CodeGen) []const u8 {
        return self.output.items;
    }

    // ============================================================
    // Program emission
    // ============================================================

    pub fn emitProgram(self: *CodeGen, program: *const ir.Program) !void {
        // File header
        try self.write("// Generated by Zap compiler\n");
        try self.write("const std = @import(\"std\");\n");
        try self.write("const zap_runtime = @import(\"zap_runtime\");\n");
        try self.write("\n");

        for (program.functions) |func| {
            try self.emitFunction(&func);
            try self.write("\n");
        }
    }

    // ============================================================
    // Function emission
    // ============================================================

    fn emitFunction(self: *CodeGen, func: *const ir.Function) !void {
        // Function signature
        try self.write("fn ");
        try self.write(func.name);
        try self.write("(");

        for (func.params, 0..) |param, i| {
            if (i > 0) try self.write(", ");
            try self.write(param.name);
            try self.write(": ");
            try self.emitZigType(&param.type_expr);
        }

        try self.write(") ");
        try self.emitZigType(&func.return_type);
        try self.write(" {\n");
        self.indent_level += 1;

        // Emit body blocks
        for (func.body) |block| {
            try self.emitBlock(&block);
        }

        self.indent_level -= 1;
        try self.write("}\n");
    }

    fn emitBlock(self: *CodeGen, block: *const ir.Block) !void {
        for (block.instructions) |instr| {
            try self.emitInstruction(&instr);
        }
    }

    // ============================================================
    // Instruction emission
    // ============================================================

    fn emitInstruction(self: *CodeGen, instr: *const ir.Instruction) !void {
        switch (instr.*) {
            .const_int => |ci| {
                try self.writeIndent();
                try self.writeLocal(ci.dest);
                try self.write(" = ");
                try self.writeInt(ci.value);
                try self.write(";\n");
            },
            .const_float => |cf| {
                try self.writeIndent();
                try self.writeLocal(cf.dest);
                try self.write(" = ");
                try self.writeFloat(cf.value);
                try self.write(";\n");
            },
            .const_string => |cs| {
                try self.writeIndent();
                try self.writeLocal(cs.dest);
                try self.write(" = \"");
                try self.write(cs.value);
                try self.write("\";\n");
            },
            .const_bool => |cb| {
                try self.writeIndent();
                try self.writeLocal(cb.dest);
                try self.write(if (cb.value) " = true;\n" else " = false;\n");
            },
            .const_atom => |ca| {
                try self.writeIndent();
                try self.writeLocal(ca.dest);
                try self.write(" = .@\"");
                try self.write(ca.value);
                try self.write("\";\n");
            },
            .const_nil => |dest| {
                try self.writeIndent();
                try self.writeLocal(dest);
                try self.write(" = null;\n");
            },
            .local_get => |lg| {
                try self.writeIndent();
                try self.writeLocal(lg.dest);
                try self.write(" = ");
                try self.writeLocal(lg.source);
                try self.write(";\n");
            },
            .local_set => |ls| {
                try self.writeIndent();
                try self.writeLocal(ls.dest);
                try self.write(" = ");
                try self.writeLocal(ls.value);
                try self.write(";\n");
            },
            .param_get => |pg| {
                try self.writeIndent();
                try self.writeLocal(pg.dest);
                try self.write(" = ");
                try self.writeParam(pg.index);
                try self.write(";\n");
            },
            .call_direct => |cd| {
                try self.writeIndent();
                try self.writeLocal(cd.dest);
                try self.write(" = func_");
                try self.writeInt(@intCast(cd.function));
                try self.write("(");
                for (cd.args, 0..) |arg, i| {
                    if (i > 0) try self.write(", ");
                    try self.writeLocal(arg);
                }
                try self.write(");\n");
            },
            .call_closure => |cc| {
                try self.writeIndent();
                try self.writeLocal(cc.dest);
                try self.write(" = ");
                try self.writeLocal(cc.callee);
                try self.write("(");
                for (cc.args, 0..) |arg, i| {
                    if (i > 0) try self.write(", ");
                    try self.writeLocal(arg);
                }
                try self.write(");\n");
            },
            .call_dispatch => |cd_disp| {
                try self.writeIndent();
                try self.writeLocal(cd_disp.dest);
                try self.write(" = dispatch_");
                try self.writeInt(@intCast(cd_disp.group_id));
                try self.write("(");
                for (cd_disp.args, 0..) |arg, i| {
                    if (i > 0) try self.write(", ");
                    try self.writeLocal(arg);
                }
                try self.write(");\n");
            },
            .cond_branch => |cb| {
                try self.writeIndent();
                try self.write("if (");
                try self.writeLocal(cb.condition);
                try self.write(") goto label_");
                try self.writeInt(@intCast(cb.then_target));
                try self.write(" else goto label_");
                try self.writeInt(@intCast(cb.else_target));
                try self.write(";\n");
            },
            .branch => |br| {
                try self.writeIndent();
                try self.write("// goto label_");
                try self.writeInt(@intCast(br.target));
                try self.write("\n");
            },
            .ret => |r| {
                try self.writeIndent();
                try self.write("return");
                if (r.value) |v| {
                    try self.write(" ");
                    try self.writeLocal(v);
                }
                try self.write(";\n");
            },
            .tuple_init => |ti| {
                try self.writeIndent();
                try self.writeLocal(ti.dest);
                try self.write(" = .{");
                for (ti.elements, 0..) |elem, i| {
                    if (i > 0) try self.write(", ");
                    try self.writeLocal(elem);
                }
                try self.write("};\n");
            },
            .list_init => |li| {
                try self.writeIndent();
                try self.writeLocal(li.dest);
                try self.write(" = &.{");
                for (li.elements, 0..) |elem, i| {
                    if (i > 0) try self.write(", ");
                    try self.writeLocal(elem);
                }
                try self.write("};\n");
            },
            .match_fail => |mf| {
                try self.writeIndent();
                try self.write("@panic(\"");
                try self.write(mf.message);
                try self.write("\");\n");
            },
            .make_closure => |mc| {
                try self.writeIndent();
                try self.writeLocal(mc.dest);
                try self.write(" = makeClosure(func_");
                try self.writeInt(@intCast(mc.function));
                try self.write(", .{");
                for (mc.captures, 0..) |cap, i| {
                    if (i > 0) try self.write(", ");
                    try self.writeLocal(cap);
                }
                try self.write("});\n");
            },
            .call_builtin => |cb| {
                try self.writeIndent();
                try self.writeLocal(cb.dest);
                try self.write(" = zap_runtime.Prelude.");
                try self.write(cb.name);
                try self.write("(");
                for (cb.args, 0..) |arg, i| {
                    if (i > 0) try self.write(", ");
                    try self.writeLocal(arg);
                }
                try self.write(");\n");
            },
            else => {
                try self.writeIndent();
                try self.write("// unhandled instruction\n");
            },
        }
    }

    // ============================================================
    // Type emission
    // ============================================================

    fn emitZigType(self: *CodeGen, zig_type: *const ir.ZigType) !void {
        switch (zig_type.*) {
            .void => try self.write("void"),
            .bool_type => try self.write("bool"),
            .i8 => try self.write("i8"),
            .i16 => try self.write("i16"),
            .i32 => try self.write("i32"),
            .i64 => try self.write("i64"),
            .u8 => try self.write("u8"),
            .u16 => try self.write("u16"),
            .u32 => try self.write("u32"),
            .u64 => try self.write("u64"),
            .f16 => try self.write("f16"),
            .f32 => try self.write("f32"),
            .f64 => try self.write("f64"),
            .usize => try self.write("usize"),
            .isize => try self.write("isize"),
            .string => try self.write("[]const u8"),
            .atom => try self.write("zap_runtime.Atom"),
            .nil => try self.write("?void"),
            .any => try self.write("anytype"),
            .struct_ref => |name| try self.write(name),
            .tagged_union => |name| try self.write(name),
            else => try self.write("anytype"),
        }
    }

    // ============================================================
    // Write helpers
    // ============================================================

    fn write(self: *CodeGen, text: []const u8) !void {
        try self.output.appendSlice(self.allocator, text);
    }

    fn writeIndent(self: *CodeGen) !void {
        var i: u32 = 0;
        while (i < self.indent_level) : (i += 1) {
            try self.write("    ");
        }
    }

    fn writeLocal(self: *CodeGen, id: ir.LocalId) !void {
        const str = try std.fmt.allocPrint(self.allocator, "__local_{d}", .{id});
        try self.write(str);
    }

    fn writeParam(self: *CodeGen, idx: u32) !void {
        const str = try std.fmt.allocPrint(self.allocator, "__param_{d}", .{idx});
        try self.write(str);
    }

    fn writeInt(self: *CodeGen, value: i64) !void {
        const str = try std.fmt.allocPrint(self.allocator, "{d}", .{value});
        try self.write(str);
    }

    fn writeFloat(self: *CodeGen, value: f64) !void {
        const str = try std.fmt.allocPrint(self.allocator, "{d}", .{value});
        try self.write(str);
    }
};

// ============================================================
// Tests
// ============================================================

const Parser = @import("parser.zig").Parser;
const Collector = @import("collector.zig").Collector;
const hir_mod = @import("hir.zig");

test "codegen simple function" {
    const source =
        \\def add(x :: i64, y :: i64) :: i64 do
        \\  x + y
        \\end
    ;

    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var parser = Parser.init(alloc, source);
    defer parser.deinit();
    const program = try parser.parseProgram();

    var collector = Collector.init(alloc, &parser.interner);
    defer collector.deinit();
    try collector.collectProgram(&program);

    var type_store = types_mod.TypeStore.init(alloc, &parser.interner);
    defer type_store.deinit();

    var hir_builder = hir_mod.HirBuilder.init(alloc, &parser.interner, &collector.graph, &type_store);
    defer hir_builder.deinit();
    const hir_program = try hir_builder.buildProgram(&program);

    var ir_builder = ir.IrBuilder.init(alloc, &parser.interner);
    defer ir_builder.deinit();
    const ir_program = try ir_builder.buildProgram(&hir_program);

    var codegen = CodeGen.init(alloc);
    defer codegen.deinit();
    try codegen.emitProgram(&ir_program);

    const output = codegen.getOutput();
    // Should contain function definition
    try std.testing.expect(std.mem.indexOf(u8, output, "fn add") != null);
    // Should contain return statement
    try std.testing.expect(std.mem.indexOf(u8, output, "return") != null);
}

test "codegen produces valid structure" {
    const source =
        \\def foo() do
        \\  42
        \\end
    ;

    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var parser = Parser.init(alloc, source);
    defer parser.deinit();
    const program = try parser.parseProgram();

    var collector = Collector.init(alloc, &parser.interner);
    defer collector.deinit();
    try collector.collectProgram(&program);

    var type_store = types_mod.TypeStore.init(alloc, &parser.interner);
    defer type_store.deinit();

    var hir_builder = hir_mod.HirBuilder.init(alloc, &parser.interner, &collector.graph, &type_store);
    defer hir_builder.deinit();
    const hir_program = try hir_builder.buildProgram(&program);

    var ir_builder = ir.IrBuilder.init(alloc, &parser.interner);
    defer ir_builder.deinit();
    const ir_program = try ir_builder.buildProgram(&hir_program);

    var codegen = CodeGen.init(alloc);
    defer codegen.deinit();
    try codegen.emitProgram(&ir_program);

    const output = codegen.getOutput();
    // Should contain header
    try std.testing.expect(std.mem.indexOf(u8, output, "Generated by Zap compiler") != null);
    // Should contain the literal 42
    try std.testing.expect(std.mem.indexOf(u8, output, "42") != null);
}
