const std = @import("std");
const ast = @import("ast.zig");

// ============================================================
// Desugaring pass
//
// Runs after macro expansion, before name resolution.
// Transforms syntactic sugar into core forms:
//
//   1. Pipe `x |> f(y)` → `f(x, y)`
//   2. Unwrap `expr!` → `case expr do {:ok, v} -> v; {:error, e} -> panic(e) end`
//   3. String interpolation `"hello #{name}"` → `"hello " <> to_string(name)`
// ============================================================

const scope_mod = @import("scope.zig");

pub const Desugarer = struct {
    allocator: std.mem.Allocator,
    interner: *ast.StringInterner,
    graph: ?*const scope_mod.ScopeGraph = null,
    for_counter: u32 = 0,
    /// Helper functions generated by for comprehension desugaring.
    /// Flushed into the struct's items after desugaring each struct.
    pending_helpers: std.ArrayList(ast.StructItem) = .empty,
    /// Current struct scope during desugaring — used for import resolution.
    current_struct_scope: ?scope_mod.ScopeId = null,
    /// Set while desugaring inside a `macro` / `priv_macro` declaration's
    /// body. Macro bodies are compile-time templates evaluated by the
    /// macro engine (`src/macro_eval.zig`), so constructs that would
    /// normally be lowered to runtime helpers — `for` comprehensions in
    /// particular — must NOT be lifted out as `__for_N` private
    /// functions. The macro engine handles `for` directly via
    /// `forComprehensionIntrinsic`. Lifting would emit a runtime helper
    /// whose body still references comptime-only intrinsics (`elem`,
    /// `list_at`, etc.), tripping spurious "function not found"
    /// diagnostics during type-checking.
    in_macro_body: bool = false,

    pub fn init(allocator: std.mem.Allocator, interner: *ast.StringInterner, graph: ?*const scope_mod.ScopeGraph) Desugarer {
        return .{
            .allocator = allocator,
            .interner = interner,
            .graph = graph,
        };
    }

    // ============================================================
    // Program desugaring
    // ============================================================

    pub fn desugarProgram(self: *Desugarer, program: *const ast.Program) !ast.Program {
        var new_structs: std.ArrayList(ast.StructDecl) = .empty;
        for (program.structs) |mod| {
            try new_structs.append(self.allocator, try self.desugarStruct(&mod));
        }

        var new_top_items: std.ArrayList(ast.TopItem) = .empty;
        for (program.top_items) |item| {
            try new_top_items.append(self.allocator, try self.desugarTopItem(item));
        }

        return .{
            .structs = try new_structs.toOwnedSlice(self.allocator),
            .top_items = try new_top_items.toOwnedSlice(self.allocator),
        };
    }

    fn desugarStruct(self: *Desugarer, mod: *const ast.StructDecl) !ast.StructDecl {
        self.pending_helpers = .empty;
        // Set current struct scope for import resolution
        if (self.graph) |g| {
            self.current_struct_scope = g.findStructScope(mod.name);
        }
        defer self.current_struct_scope = null;
        var new_items: std.ArrayList(ast.StructItem) = .empty;
        for (mod.items) |item| {
            try new_items.append(self.allocator, try self.desugarStructItem(item));
        }
        // Append helper functions generated by for comprehensions
        for (self.pending_helpers.items) |helper| {
            try new_items.append(self.allocator, helper);
        }
        try self.appendSynthesizedRunIfNeeded(mod, &new_items);
        return .{
            .meta = mod.meta,
            .name = mod.name,
            .parent = mod.parent,
            .items = try new_items.toOwnedSlice(self.allocator),
            .fields = mod.fields,
            .is_private = mod.is_private,
        };
    }

    fn appendSynthesizedRunIfNeeded(
        self: *Desugarer,
        mod: *const ast.StructDecl,
        items: *std.ArrayList(ast.StructItem),
    ) !void {
        const run_name = try self.interner.intern("run");
        var struct_level_exprs: std.ArrayList(*const ast.Expr) = .empty;

        for (items.items) |item| {
            switch (item) {
                .function => |func| {
                    if (self.functionHasArity(func, run_name, 0)) return;
                },
                .priv_function => |func| {
                    if (self.functionHasArity(func, run_name, 0)) return;
                },
                .struct_level_expr => |expr| try struct_level_exprs.append(self.allocator, expr),
                else => {},
            }
        }

        if (struct_level_exprs.items.len == 0) return;

        const statements = try self.allocator.alloc(ast.Stmt, struct_level_exprs.items.len);
        for (struct_level_exprs.items, 0..) |expr, index| {
            statements[index] = .{ .expr = expr };
        }

        const string_type_name = try self.nativeStringTypeName();
        const return_type = try self.create(ast.TypeExpr, .{
            .name = .{
                .meta = mod.meta,
                .name = string_type_name,
                .args = &.{},
            },
        });

        const clauses = try self.allocator.alloc(ast.FunctionClause, 1);
        clauses[0] = .{
            .meta = mod.meta,
            .params = &.{},
            .return_type = return_type,
            .refinement = null,
            .body = statements,
        };

        const run_decl = try self.create(ast.FunctionDecl, .{
            .meta = mod.meta,
            .name = run_name,
            .name_expr = null,
            .clauses = clauses,
            .visibility = .public,
        });
        try items.append(self.allocator, .{ .function = run_decl });
    }

    fn functionHasArity(self: *const Desugarer, func: *const ast.FunctionDecl, name: ast.StringId, arity: usize) bool {
        _ = self;
        if (func.name != name) return false;
        for (func.clauses) |clause| {
            if (clause.params.len == arity) return true;
        }
        return false;
    }

    fn nativeStringTypeName(self: *Desugarer) !ast.StringId {
        if (self.graph) |graph| {
            if (graph.nativeTypeStructName(.string)) |name| return name;
        }
        return self.interner.intern("String");
    }

    fn desugarTopItem(self: *Desugarer, item: ast.TopItem) !ast.TopItem {
        return switch (item) {
            .function => |func| .{ .function = try self.desugarFunctionDecl(func) },
            .priv_function => |func| .{ .priv_function = try self.desugarFunctionDecl(func) },
            .macro => |mac| .{ .macro = try self.desugarMacroDecl(mac) },
            .priv_macro => |mac| .{ .priv_macro = try self.desugarMacroDecl(mac) },
            else => item,
        };
    }

    fn desugarStructItem(self: *Desugarer, item: ast.StructItem) !ast.StructItem {
        return switch (item) {
            .function => |func| .{ .function = try self.desugarFunctionDecl(func) },
            .priv_function => |func| .{ .priv_function = try self.desugarFunctionDecl(func) },
            .macro => |mac| .{ .macro = try self.desugarMacroDecl(mac) },
            .priv_macro => |mac| .{ .priv_macro = try self.desugarMacroDecl(mac) },
            .struct_level_expr => |expr| .{ .struct_level_expr = try self.desugarExpr(expr) },
            else => item,
        };
    }

    /// Desugar a macro declaration. Identical to `desugarFunctionDecl`
    /// except for setting `in_macro_body` so that nested `for`
    /// comprehensions are not lifted into `__for_N` private functions.
    /// Macro bodies are compile-time templates evaluated by the macro
    /// engine; the `for` is handled by `forComprehensionIntrinsic` in
    /// `src/macro_eval.zig`, so a runtime helper would be both useless
    /// and a source of spurious "function not found" diagnostics for
    /// the comptime-only intrinsics in the body.
    fn desugarMacroDecl(self: *Desugarer, mac: *const ast.FunctionDecl) !*const ast.FunctionDecl {
        const prev = self.in_macro_body;
        self.in_macro_body = true;
        defer self.in_macro_body = prev;
        return self.desugarFunctionDecl(mac);
    }

    // ============================================================
    // Function declaration desugaring
    // ============================================================

    fn desugarFunctionDecl(self: *Desugarer, func: *const ast.FunctionDecl) !*const ast.FunctionDecl {
        var new_clauses: std.ArrayList(ast.FunctionClause) = .empty;
        for (func.clauses) |clause| {
            try new_clauses.append(self.allocator, .{
                .meta = clause.meta,
                .params = clause.params,
                .return_type = clause.return_type,
                .refinement = if (clause.refinement) |r| try self.desugarExpr(r) else null,
                .body = if (clause.body) |body| try self.desugarBlock(body) else null,
            });
        }
        return try self.create(ast.FunctionDecl, .{
            .meta = func.meta,
            .name = func.name,
            .clauses = try new_clauses.toOwnedSlice(self.allocator),
            .visibility = func.visibility,
        });
    }

    // ============================================================
    // Block desugaring
    // ============================================================

    fn desugarBlock(self: *Desugarer, stmts: []const ast.Stmt) anyerror![]const ast.Stmt {
        var new_stmts: std.ArrayList(ast.Stmt) = .empty;
        for (stmts) |stmt| {
            try new_stmts.append(self.allocator, try self.desugarStmt(stmt));
        }
        return new_stmts.toOwnedSlice(self.allocator);
    }

    fn desugarStmt(self: *Desugarer, stmt: ast.Stmt) anyerror!ast.Stmt {
        return switch (stmt) {
            .expr => |expr| .{ .expr = try self.desugarExpr(expr) },
            .assignment => |assign| .{
                .assignment = try self.create(ast.Assignment, .{
                    .meta = assign.meta,
                    .pattern = assign.pattern,
                    .value = try self.desugarExpr(assign.value),
                }),
            },
            .function_decl => |func| .{ .function_decl = try self.desugarFunctionDecl(func) },
            .macro_decl => |mac| .{ .macro_decl = try self.desugarMacroDecl(mac) },
            .import_decl => stmt,
            .attribute => |attr| .{
                .attribute = try self.create(ast.AttributeDecl, .{
                    .meta = attr.meta,
                    .name = attr.name,
                    .type_expr = attr.type_expr,
                    .value = if (attr.value) |value| try self.desugarExpr(value) else null,
                }),
            },
        };
    }

    // ============================================================
    // Expression desugaring
    // ============================================================

    fn desugarExpr(self: *Desugarer, expr: *const ast.Expr) anyerror!*const ast.Expr {
        switch (expr.*) {
            // Pipe: desugared during macro expansion (Kernel.|> macro)
            .pipe => |pe| {
                const lhs = try self.desugarExpr(pe.lhs);
                const rhs = try self.desugarExpr(pe.rhs);
                return try self.create(ast.Expr, .{
                    .pipe = .{ .meta = pe.meta, .lhs = lhs, .rhs = rhs },
                });
            },

            // Unwrap: expr! → optional force-unwrap (panics if nil)
            // String interpolation: "hello #{name}" → "hello " <> to_string(name)
            .string_interpolation => |si| {
                return self.desugarStringInterpolation(&si);
            },

            // Recurse into compound expressions
            .binary_op => |bo| {
                const new_lhs = try self.desugarExpr(bo.lhs);
                const new_rhs = try self.desugarExpr(bo.rhs);
                // `value in collection` desugars to `Membership.member?(collection, value)`
                // so the in operator dispatches through the protocol like every
                // other type-polymorphic operation. The HIR builder rewrites
                // the protocol call to the matching impl based on `collection`'s
                // inferred type. Note arg order: collection first, then value.
                if (bo.op == .in_op) {
                    const interner_mut: *ast.StringInterner = @constCast(self.interner);
                    const proto_name = try interner_mut.intern("Membership");
                    const fn_name = try interner_mut.intern("member?");
                    const parts = try self.allocator.alloc(ast.StringId, 1);
                    parts[0] = proto_name;
                    const mod_ref = try self.create(ast.Expr, .{
                        .struct_ref = .{ .meta = bo.meta, .name = .{ .parts = parts, .span = bo.meta.span } },
                    });
                    const callee = try self.create(ast.Expr, .{
                        .field_access = .{ .meta = bo.meta, .object = mod_ref, .field = fn_name },
                    });
                    return try self.create(ast.Expr, .{
                        .call = .{
                            .meta = bo.meta,
                            .callee = callee,
                            .args = try self.allocSlice(*const ast.Expr, &.{ new_rhs, new_lhs }),
                        },
                    });
                }
                return try self.create(ast.Expr, .{
                    .binary_op = .{
                        .meta = bo.meta,
                        .op = bo.op,
                        .lhs = new_lhs,
                        .rhs = new_rhs,
                    },
                });
            },
            .unary_op => |uo| {
                return try self.create(ast.Expr, .{
                    .unary_op = .{
                        .meta = uo.meta,
                        .op = uo.op,
                        .operand = try self.desugarExpr(uo.operand),
                    },
                });
            },
            .call => |call| {
                var new_args: std.ArrayList(*const ast.Expr) = .empty;
                for (call.args) |arg| {
                    try new_args.append(self.allocator, try self.desugarExpr(arg));
                }
                const desugared_args = try new_args.toOwnedSlice(self.allocator);

                // Elixir-style import resolution: bare calls like `sleep(150)`
                // are rewritten to qualified calls `Kernel.sleep(150)` when the
                // function is found in an imported struct (including auto-imported
                // Kernel). This happens at the AST level, before HIR lowering.
                if (call.callee.* == .var_ref) {
                    const name = call.callee.var_ref.name;
                    const arity: u32 = @intCast(call.args.len);
                    if (self.resolveImportedStruct(name, arity)) |mod_name| {
                        // Rewrite: var_ref("sleep") → field_access(struct_ref("Kernel"), "sleep")
                        const mod_ref_expr = try self.create(ast.Expr, .{
                            .struct_ref = .{
                                .meta = call.meta,
                                .name = mod_name,
                            },
                        });
                        const qualified_callee = try self.create(ast.Expr, .{
                            .field_access = .{
                                .meta = call.meta,
                                .object = mod_ref_expr,
                                .field = name,
                            },
                        });
                        return try self.create(ast.Expr, .{
                            .call = .{
                                .meta = call.meta,
                                .callee = qualified_callee,
                                .args = desugared_args,
                            },
                        });
                    }
                }

                const callee = try self.desugarExpr(call.callee);
                return try self.create(ast.Expr, .{
                    .call = .{
                        .meta = call.meta,
                        .callee = callee,
                        .args = desugared_args,
                    },
                });
            },
            .anonymous_function => |anon| {
                return try self.create(ast.Expr, .{
                    .anonymous_function = .{
                        .meta = anon.meta,
                        .decl = try self.desugarFunctionDecl(anon.decl),
                    },
                });
            },
            // if_expr and cond_expr are expanded to case by the
            // macro engine (Kernel macros / special forms) before desugaring.
            // They should not reach this point.
            .case_expr => |ce| {
                var new_clauses: std.ArrayList(ast.CaseClause) = .empty;
                for (ce.clauses) |clause| {
                    try new_clauses.append(self.allocator, .{
                        .meta = clause.meta,
                        .pattern = clause.pattern,
                        .type_annotation = clause.type_annotation,
                        .guard = if (clause.guard) |g| try self.desugarExpr(g) else null,
                        .body = try self.desugarBlock(clause.body),
                    });
                }
                return try self.create(ast.Expr, .{
                    .case_expr = .{
                        .meta = ce.meta,
                        .scrutinee = try self.desugarExpr(ce.scrutinee),
                        .clauses = try new_clauses.toOwnedSlice(self.allocator),
                    },
                });
            },
            .block => |blk| {
                return try self.create(ast.Expr, .{
                    .block = .{
                        .meta = blk.meta,
                        .stmts = try self.desugarBlock(blk.stmts),
                    },
                });
            },

            // Error pipe: pass through to HIR builder. Transform function handlers
            // into block handlers so the handler call is a top-level expression.
            .error_pipe => |ep| {
                const chain = try self.desugarExpr(ep.chain);
                const handler: ast.ErrorHandler = switch (ep.handler) {
                    .function => |func| blk: {
                        // ~> handle_error() → ~> { __err -> handle_error(__err) }
                        // The unmatched value is injected as the first argument.
                        const desugared_func = try self.desugarExpr(func);
                        const err_name = try self.interner.intern("__err");
                        const err_ref = try self.create(ast.Expr, .{
                            .var_ref = .{ .meta = ep.meta, .name = err_name },
                        });

                        // Inject __err as first argument into the handler call
                        const call_expr = if (desugared_func.* == .call) ce: {
                            const call = desugared_func.call;
                            var new_args: std.ArrayList(*const ast.Expr) = .empty;
                            try new_args.append(self.allocator, err_ref);
                            for (call.args) |arg| {
                                try new_args.append(self.allocator, arg);
                            }
                            break :ce try self.create(ast.Expr, .{
                                .call = .{
                                    .meta = call.meta,
                                    .callee = call.callee,
                                    .args = try new_args.toOwnedSlice(self.allocator),
                                },
                            });
                        } else
                            // Bare function ref: wrap as call with __err
                            try self.create(ast.Expr, .{
                                .call = .{
                                    .meta = ep.meta,
                                    .callee = desugared_func,
                                    .args = try self.allocSlice(*const ast.Expr, &.{err_ref}),
                                },
                            });

                        const body = try self.allocSlice(ast.Stmt, &.{.{ .expr = call_expr }});
                        const pattern = try self.create(ast.Pattern, .{
                            .bind = .{ .meta = ep.meta, .name = err_name },
                        });
                        const clauses = try self.allocSlice(ast.CaseClause, &.{
                            .{ .meta = ep.meta, .pattern = pattern, .type_annotation = null, .guard = null, .body = body },
                        });
                        break :blk .{ .block = clauses };
                    },
                    .block => |clauses| blk: {
                        var new_clauses: std.ArrayList(ast.CaseClause) = .empty;
                        for (clauses) |clause| {
                            try new_clauses.append(self.allocator, .{
                                .meta = clause.meta,
                                .pattern = clause.pattern,
                                .type_annotation = clause.type_annotation,
                                .guard = if (clause.guard) |guard| try self.desugarExpr(guard) else null,
                                .body = try self.desugarBlock(clause.body),
                            });
                        }
                        break :blk .{ .block = try new_clauses.toOwnedSlice(self.allocator) };
                    },
                };
                return try self.create(ast.Expr, .{
                    .error_pipe = .{
                        .meta = ep.meta,
                        .chain = chain,
                        .handler = handler,
                    },
                });
            },

            // Map update: %{map | key: val, ...} → Updatable.update chains.
            // Routed through the protocol so any user type implementing
            // `Updatable.update/3` can opt in to the `%{x | k: v}` syntax.
            // The HIR builder rewrites the protocol call to the concrete
            // impl based on `result`'s inferred type.
            .map => |me| {
                if (me.update_source) |source| {
                    var result = try self.desugarExpr(source);
                    const interner_mut: *ast.StringInterner = @constCast(self.interner);
                    const proto_name = try interner_mut.intern("Updatable");
                    const fn_name = try interner_mut.intern("update");
                    for (me.fields) |field| {
                        const parts = try self.allocator.alloc(ast.StringId, 1);
                        parts[0] = proto_name;
                        const mod_ref = try self.create(ast.Expr, .{
                            .struct_ref = .{ .meta = me.meta, .name = .{ .parts = parts, .span = me.meta.span } },
                        });
                        const callee = try self.create(ast.Expr, .{
                            .field_access = .{ .meta = me.meta, .object = mod_ref, .field = fn_name },
                        });
                        result = try self.create(ast.Expr, .{
                            .call = .{
                                .meta = me.meta,
                                .callee = callee,
                                .args = try self.allocSlice(*const ast.Expr, &.{
                                    result,
                                    try self.desugarExpr(field.key),
                                    try self.desugarExpr(field.value),
                                }),
                            },
                        });
                    }
                    return result;
                }
                return expr;
            },

            // For comprehension → block with recursive helper function + call
            .for_expr => |fe| {
                return self.desugarForExpr(&fe);
            },

            // List cons expression → recurse into head and tail
            .list_cons_expr => |lce| {
                return try self.create(ast.Expr, .{
                    .list_cons_expr = .{
                        .meta = lce.meta,
                        .head = try self.desugarExpr(lce.head),
                        .tail = try self.desugarExpr(lce.tail),
                    },
                });
            },

            // Struct expression: desugar update syntax %Name{old | field: val}
            .struct_expr => |se| {
                // Recurse into field values
                var new_fields: std.ArrayList(ast.StructField) = .empty;
                for (se.fields) |field| {
                    try new_fields.append(self.allocator, .{
                        .name = field.name,
                        .value = try self.desugarExpr(field.value),
                    });
                }

                if (se.update_source) |source| {
                    const desugared_source = try self.desugarExpr(source);
                    return try self.desugarStructUpdate(se, desugared_source, new_fields.items);
                }

                return try self.create(ast.Expr, .{
                    .struct_expr = .{
                        .meta = se.meta,
                        .struct_name = se.struct_name,
                        .update_source = null,
                        .fields = try new_fields.toOwnedSlice(self.allocator),
                    },
                });
            },

            .range => |re| {
                // Rewrite `start..end[..step]` into `%Range{start: ..., end: ..., step: ...}`.
                // Range is a Zap struct (lib/range.zap); the compiler doesn't need
                // a dedicated AST shape — desugaring it here keeps HIR oblivious to
                // the struct's identity. Step validation (must be > 0) lives in
                // the type checker since this rewrite always runs before that pass.
                const new_start = try self.desugarExpr(re.start);
                const new_end = try self.desugarExpr(re.end);
                const step_expr: *const ast.Expr = if (re.step) |s|
                    try self.desugarExpr(s)
                else
                    try self.create(ast.Expr, .{
                        .int_literal = .{ .meta = re.meta, .value = 1 },
                    });

                const interner_mut: *ast.StringInterner = @constCast(self.interner);
                const range_name = try interner_mut.intern("Range");
                const start_name = try interner_mut.intern("start");
                const end_name = try interner_mut.intern("end");
                const step_name = try interner_mut.intern("step");

                const fields = try self.allocator.alloc(ast.StructField, 3);
                fields[0] = .{ .name = start_name, .value = new_start };
                fields[1] = .{ .name = end_name, .value = new_end };
                fields[2] = .{ .name = step_name, .value = step_expr };

                const parts = try self.allocator.alloc(ast.StringId, 1);
                parts[0] = range_name;

                return self.create(ast.Expr, .{
                    .struct_expr = .{
                        .meta = re.meta,
                        .struct_name = .{ .parts = parts, .span = re.meta.span },
                        .update_source = null,
                        .fields = fields,
                    },
                });
            },

            // ----- Compound expressions: recurse so transformations
            //       (pipe rewriting, string interpolation, etc.) inside
            //       compound shapes are not silently lost.

            .tuple => |te| {
                var new_elements: std.ArrayList(*const ast.Expr) = .empty;
                for (te.elements) |elem| {
                    try new_elements.append(self.allocator, try self.desugarExpr(elem));
                }
                return try self.create(ast.Expr, .{
                    .tuple = .{
                        .meta = te.meta,
                        .elements = try new_elements.toOwnedSlice(self.allocator),
                    },
                });
            },
            .list => |le| {
                var new_elements: std.ArrayList(*const ast.Expr) = .empty;
                for (le.elements) |elem| {
                    try new_elements.append(self.allocator, try self.desugarExpr(elem));
                }
                return try self.create(ast.Expr, .{
                    .list = .{
                        .meta = le.meta,
                        .elements = try new_elements.toOwnedSlice(self.allocator),
                    },
                });
            },
            .field_access => |fa| {
                return try self.create(ast.Expr, .{
                    .field_access = .{
                        .meta = fa.meta,
                        .object = try self.desugarExpr(fa.object),
                        .field = fa.field,
                    },
                });
            },
            .unwrap => |uw| {
                return try self.desugarUnwrap(try self.desugarExpr(uw.expr), uw.meta);
            },
            .panic_expr => |pe| {
                return try self.create(ast.Expr, .{
                    .panic_expr = .{
                        .meta = pe.meta,
                        .message = try self.desugarExpr(pe.message),
                    },
                });
            },
            .type_annotated => |ta| {
                return try self.create(ast.Expr, .{
                    .type_annotated = .{
                        .meta = ta.meta,
                        .expr = try self.desugarExpr(ta.expr),
                        .type_expr = ta.type_expr,
                    },
                });
            },

            // ----- Leaf nodes — no recursion, no transformation.
            //       Listed explicitly so adding a new Expr variant
            //       triggers a switch-exhaustiveness compile error here
            //       and forces a deliberate decision instead of silently
            //       falling through `else => return expr`.

            .int_literal,
            .float_literal,
            .string_literal,
            .atom_literal,
            .bool_literal,
            .nil_literal,
            .var_ref,
            .struct_ref,
            .intrinsic,
            .attr_ref,
            .binary_literal,
            .function_ref,
            => return expr,

            // ----- Macro-internal AST nodes — these are placeholders
            //       inside `quote { ... }` bodies and should NEVER be
            //       desugared. The macro engine consumes them.

            .quote_expr,
            .unquote_expr,
            .unquote_splicing_expr,
            => return expr,

            // ----- Control-flow forms expanded to `case` by the macro
            //       engine before desugaring runs. Reaching this point
            //       indicates a pipeline ordering bug, not a normal
            //       desugaring case — keep them passthrough as a
            //       defensive measure but flag for future tightening.

            .if_expr,
            .cond_expr,
            => return expr,
        }
    }

    /// Expand struct update syntax: %Name{old | x: new_x}
    /// Looks up the struct definition to get all field names, then generates
    /// a complete struct init where unchanged fields use old.field_name.
    fn desugarStructUpdate(
        self: *Desugarer,
        original: ast.StructExpr,
        source: *const ast.Expr,
        override_fields: []const ast.StructField,
    ) anyerror!*const ast.Expr {
        // Look up the struct definition from the scope graph
        const struct_decl = self.findStructDecl(original.struct_name) orelse {
            // Can't find the struct definition — pass through unchanged.
            // The HIR builder will report the proper error.
            return try self.create(ast.Expr, .{
                .struct_expr = .{
                    .meta = original.meta,
                    .struct_name = original.struct_name,
                    .update_source = source,
                    .fields = override_fields,
                },
            });
        };

        // Build a complete field list including inherited fields.
        // For each field, either use the override value or generate
        // a field_access on the source.
        var all_fields: std.ArrayList(ast.StructField) = .empty;
        const all_def_fields = self.collectAllStructFields(struct_decl);

        for (all_def_fields) |def_field| {
            // Check if this field is overridden
            var override_value: ?*const ast.Expr = null;
            for (override_fields) |of| {
                if (of.name == def_field.name) {
                    override_value = of.value;
                    break;
                }
            }

            if (override_value) |value| {
                try all_fields.append(self.allocator, .{
                    .name = def_field.name,
                    .value = value,
                });
            } else {
                // Generate source.field_name
                const field_access = try self.create(ast.Expr, .{
                    .field_access = .{
                        .meta = original.meta,
                        .object = source,
                        .field = def_field.name,
                    },
                });
                try all_fields.append(self.allocator, .{
                    .name = def_field.name,
                    .value = field_access,
                });
            }
        }

        return try self.create(ast.Expr, .{
            .struct_expr = .{
                .meta = original.meta,
                .struct_name = original.struct_name,
                .update_source = null,
                .fields = try all_fields.toOwnedSlice(self.allocator),
            },
        });
    }

    /// Find a struct declaration by struct name from the scope graph.
    fn findStructDecl(self: *const Desugarer, struct_name: ast.StructName) ?*const ast.StructDecl {
        const graph = self.graph orelse return null;
        if (struct_name.parts.len == 0) return null;
        const struct_name_id = struct_name.parts[struct_name.parts.len - 1];

        if (graph.resolveTypeByName(struct_name_id)) |type_id| {
            if (type_id < graph.types.items.len) {
                const entry = graph.types.items[type_id];
                if (entry.kind == .struct_type) return entry.kind.struct_type;
            }
        }

        const name_str = self.interner.get(struct_name_id);
        for (graph.types.items) |entry| {
            if (entry.kind == .struct_type) {
                if (std.mem.eql(u8, self.interner.get(entry.name), name_str))
                    return entry.kind.struct_type;
            }
        }
        return null;
    }

    /// Collect ALL fields for a struct, including inherited fields from
    /// the extends chain. Returns fields in order: parent fields first,
    /// then own fields (matching the TypeStore's field ordering).
    fn collectAllStructFields(self: *const Desugarer, decl: *const ast.StructDecl) []const ast.StructFieldDecl {
        const graph = self.graph orelse return decl.fields;

        if (decl.parent) |parent_name_id| {
            // Find parent struct
            if (graph.resolveTypeByName(parent_name_id)) |parent_type_id| {
                if (parent_type_id < graph.types.items.len) {
                    const parent_entry = graph.types.items[parent_type_id];
                    if (parent_entry.kind == .struct_type) {
                        const parent_decl = parent_entry.kind.struct_type;
                        const parent_fields = self.collectAllStructFields(parent_decl);
                        // Merge: parent fields + own fields
                        var all_fields: std.ArrayListUnmanaged(ast.StructFieldDecl) = .empty;
                        all_fields.appendSlice(self.allocator, parent_fields) catch return decl.fields;
                        all_fields.appendSlice(self.allocator, decl.fields) catch return decl.fields;
                        return all_fields.toOwnedSlice(self.allocator) catch decl.fields;
                    }
                }
            }
        }

        return decl.fields;
    }

    // ============================================================
    // Unwrap desugaring: expr! → case expr { {:ok, v} -> v, {:error, e} -> panic(e) }
    // ============================================================

    fn desugarUnwrap(self: *Desugarer, inner: *const ast.Expr, meta: ast.NodeMeta) !*const ast.Expr {
        const v_name = try self.interner.intern("__unwrap_val");
        const e_name = try self.interner.intern("__unwrap_err");
        const ok_name = try self.interner.intern("ok");
        const error_name = try self.interner.intern("error");

        // Pattern {:ok, v}
        const ok_pattern = try self.create(ast.Pattern, .{
            .tuple = .{
                .meta = meta,
                .elements = try self.allocSlice(*const ast.Pattern, &.{
                    try self.create(ast.Pattern, .{ .literal = .{ .atom = .{ .meta = meta, .value = ok_name } } }),
                    try self.create(ast.Pattern, .{ .bind = .{ .meta = meta, .name = v_name } }),
                }),
            },
        });

        // Pattern {:error, e}
        const error_pattern = try self.create(ast.Pattern, .{
            .tuple = .{
                .meta = meta,
                .elements = try self.allocSlice(*const ast.Pattern, &.{
                    try self.create(ast.Pattern, .{ .literal = .{ .atom = .{ .meta = meta, .value = error_name } } }),
                    try self.create(ast.Pattern, .{ .bind = .{ .meta = meta, .name = e_name } }),
                }),
            },
        });

        // Body for ok: v
        const ok_body = try self.allocSlice(ast.Stmt, &.{
            .{ .expr = try self.create(ast.Expr, .{ .var_ref = .{ .meta = meta, .name = v_name } }) },
        });

        // Body for error: panic(e)
        const e_ref = try self.create(ast.Expr, .{ .var_ref = .{ .meta = meta, .name = e_name } });
        const error_body = try self.allocSlice(ast.Stmt, &.{
            .{ .expr = try self.create(ast.Expr, .{
                .panic_expr = .{ .meta = meta, .message = e_ref },
            }) },
        });

        const clauses = try self.allocSlice(ast.CaseClause, &.{
            .{ .meta = meta, .pattern = ok_pattern, .type_annotation = null, .guard = null, .body = ok_body },
            .{ .meta = meta, .pattern = error_pattern, .type_annotation = null, .guard = null, .body = error_body },
        });

        return try self.create(ast.Expr, .{
            .case_expr = .{
                .meta = meta,
                .scrutinee = inner,
                .clauses = clauses,
            },
        });
    }

    // ============================================================
    // String interpolation desugaring
    // ============================================================

    fn desugarStringInterpolation(self: *Desugarer, si: *const ast.StringInterpolation) !*const ast.Expr {
        var result: ?*const ast.Expr = null;

        for (si.parts) |part| {
            const part_expr: *const ast.Expr = switch (part) {
                .literal => |str_id| try self.create(ast.Expr, .{
                    .string_literal = .{ .meta = si.meta, .value = str_id },
                }),
                .expr => |expr| blk: {
                    const desugared = try self.desugarExpr(expr);
                    // Wrap in `Stringable.to_string(value)` — the
                    // protocol's HIR-level dispatch picks the right
                    // per-type impl (Integer, Atom, Bool, Float,
                    // String, or any user impl) at compile time based
                    // on `value`'s static type. The protocol struct
                    // name is the only stdlib name the desugarer
                    // hardcodes here, mirroring how `for` desugars
                    // through `Enumerable.next`.
                    const interner_mut: *ast.StringInterner = @constCast(self.interner);
                    const proto_name = try interner_mut.intern("Stringable");
                    const fn_name = try interner_mut.intern("to_string");
                    const proto_parts = try self.allocator.alloc(ast.StringId, 1);
                    proto_parts[0] = proto_name;
                    const proto_ref = try self.create(ast.Expr, .{
                        .struct_ref = .{
                            .meta = si.meta,
                            .name = .{ .parts = proto_parts, .span = si.meta.span },
                        },
                    });
                    const callee = try self.create(ast.Expr, .{
                        .field_access = .{
                            .meta = si.meta,
                            .object = proto_ref,
                            .field = fn_name,
                        },
                    });
                    break :blk try self.create(ast.Expr, .{
                        .call = .{
                            .meta = si.meta,
                            .callee = callee,
                            .args = try self.allocSlice(*const ast.Expr, &.{desugared}),
                        },
                    });
                },
            };

            if (result) |prev| {
                result = try self.create(ast.Expr, .{
                    .binary_op = .{
                        .meta = si.meta,
                        .op = .concat,
                        .lhs = prev,
                        .rhs = part_expr,
                    },
                });
            } else {
                result = part_expr;
            }
        }

        return result orelse try self.create(ast.Expr, .{
            .string_literal = .{
                .meta = si.meta,
                .value = try self.interner.intern(""),
            },
        });
    }

    // ============================================================
    // For comprehension desugaring
    //
    // for x <- iterable { body }
    // →
    // {
    //   fn __for_N(__state) {
    //     case Enumerable.next(__state) {
    //       {:done, _, _} -> []
    //       {:cont, x, __next} -> [body | __for_N(__next)]
    //     }
    //   }
    //   __for_N(iterable)
    // }
    //
    // The `Enumerable.next/1` call is rewritten to the matching impl's
    // `T.next(state)` at HIR build time via protocol dispatch
    // (see `HirBuilder.protocolDispatchStruct`). This is the single,
    // type-driven dispatch path — no AST-shape special-casing here.
    // Strings remain a separate path because they iterate by byte index
    // rather than through Enumerable.
    // ============================================================

    /// Resolution shape for a for-loop's destructuring slot. When the
    /// loop variable carries a type annotation, the destructure target
    /// becomes an internal bind and a type-asserted rebinding is
    /// prepended to the loop body — pushing the annotation through the
    /// same `pattern = (value :: T)` path that any user-written
    /// destructuring assignment uses. When no annotation is present, the
    /// user's pattern slots in directly with no extra binding.
    const LoopBind = struct {
        /// Pattern that goes into the cons head, cont tuple, or string
        /// per-byte slot.
        pattern: *const ast.Pattern,
        /// Statements prepended to the loop body (empty when no
        /// annotation was given).
        pre_body: []const ast.Stmt,
    };

    fn buildLoopBind(self: *Desugarer, fe: *const ast.ForExpr, meta: ast.NodeMeta) !LoopBind {
        if (fe.var_type_annotation) |ta| {
            const raw_name = try self.interner.intern("__loop_raw");
            const raw_pat = try self.create(ast.Pattern, .{
                .bind = .{ .meta = meta, .name = raw_name },
            });
            const raw_ref = try self.create(ast.Expr, .{
                .var_ref = .{ .meta = meta, .name = raw_name },
            });
            const annotated = try self.create(ast.Expr, .{
                .type_annotated = .{ .meta = meta, .expr = raw_ref, .type_expr = ta },
            });
            const assign = try self.create(ast.Assignment, .{
                .meta = meta,
                .pattern = fe.var_pattern,
                .value = annotated,
            });
            return .{
                .pattern = raw_pat,
                .pre_body = try self.allocSlice(ast.Stmt, &.{.{ .assignment = assign }}),
            };
        }
        return .{
            .pattern = fe.var_pattern,
            .pre_body = &.{},
        };
    }

    /// Build the body-statement slice for a loop arm: optional
    /// type-asserted rebinding followed by the arm's expression.
    fn loopArmBody(self: *Desugarer, pre_body: []const ast.Stmt, body_expr: *const ast.Expr) ![]const ast.Stmt {
        if (pre_body.len == 0) {
            return try self.allocSlice(ast.Stmt, &.{.{ .expr = body_expr }});
        }
        var stmts: std.ArrayList(ast.Stmt) = .empty;
        try stmts.appendSlice(self.allocator, pre_body);
        try stmts.append(self.allocator, .{ .expr = body_expr });
        return try stmts.toOwnedSlice(self.allocator);
    }

    fn desugarForExpr(self: *Desugarer, fe: *const ast.ForExpr) !*const ast.Expr {
        // Inside a macro body, leave the `for` expression intact: the
        // macro engine evaluates it directly via
        // `forComprehensionIntrinsic` in `src/macro_eval.zig`. Lifting
        // it into a runtime `__for_N` helper would emit a private
        // function whose body still references compile-time intrinsics
        // (`elem`, `list_at`, etc.), which the type checker
        // would then flag as missing functions. We still recurse into
        // the iterable, filter, and body so any nested non-for
        // desugaring (string interpolation, pipes the macro engine
        // already handled, etc.) still applies.
        if (self.in_macro_body) {
            const iterable = try self.desugarExpr(fe.iterable);
            const filter = if (fe.filter) |f| try self.desugarExpr(f) else null;
            const body = try self.desugarExpr(fe.body);
            return try self.create(ast.Expr, .{
                .for_expr = .{
                    .meta = fe.meta,
                    .var_pattern = fe.var_pattern,
                    .var_type_annotation = fe.var_type_annotation,
                    .iterable = iterable,
                    .filter = filter,
                    .body = body,
                },
            });
        }

        // All iterables route through the Enumerable protocol. The HIR
        // builder's `protocolDispatchStruct` rewrites `Enumerable.next(state)`
        // to `T.next(state)` based on `state`'s inferred type at HIR build
        // time. Strings dispatch through `lib/string/enumerable.zap` — the
        // earlier hand-rolled byte-index loop was deleted in favour of the
        // unified protocol path so every container iterates the same way.
        return self.desugarForEnumerable(fe);
    }

    /// Desugar for comprehension via the Enumerable protocol. Generates
    /// a recursive helper that scrutinises `Enumerable.next(state)` and
    /// branches on the `{:done, _, _}` / `{:cont, val, next_state}`
    /// shape:
    ///
    ///   fn __for_N(__state) {
    ///     case Enumerable.next(__state) {
    ///       {:done, _, _} -> []
    ///       {:cont, x, __next_state} -> [body | __for_N(__next_state)]
    ///     }
    ///   }
    ///
    /// The `Enumerable.next/1` invocation lowers to the matching impl's
    /// `T.next/1` at HIR build time (`HirBuilder.protocolDispatchStruct`),
    /// based on `__state`'s inferred type. This keeps the desugar pass
    /// type-agnostic — list, range, map, and user-defined Enumerables all
    /// share the same generated shape.
    fn desugarForEnumerable(self: *Desugarer, fe: *const ast.ForExpr) !*const ast.Expr {
        const meta = ast.NodeMeta{ .span = .{ .start = 0, .end = 0 } };

        const name_str = try std.fmt.allocPrint(self.allocator, "__for_{d}", .{self.for_counter});
        self.for_counter += 1;
        const helper_name = try self.interner.intern(name_str);
        const state_name = try self.interner.intern("__state");
        const next_state_name = try self.interner.intern("__next_state");

        const state_ref = try self.create(ast.Expr, .{ .var_ref = .{ .meta = meta, .name = state_name } });

        // Build `Enumerable.next(__state)`. The HIR builder rewrites this
        // protocol call to the concrete impl's `T.next(state)` based on
        // `__state`'s inferred type.
        const enum_id = try self.interner.intern("Enumerable");
        const enum_parts = try self.allocator.alloc(ast.StringId, 1);
        enum_parts[0] = enum_id;
        const mod_ref = try self.create(ast.Expr, .{
            .struct_ref = .{ .meta = meta, .name = .{ .parts = enum_parts, .span = .{ .start = 0, .end = 0 } } },
        });
        const next_field = try self.interner.intern("next");
        const next_callee = try self.create(ast.Expr, .{
            .field_access = .{ .meta = meta, .object = mod_ref, .field = next_field },
        });
        const next_call = try self.create(ast.Expr, .{
            .call = .{ .meta = meta, .callee = next_callee, .args = try self.allocSlice(*const ast.Expr, &.{state_ref}) },
        });

        // Recursive call: __for_N(__next_state)
        const next_state_ref = try self.create(ast.Expr, .{ .var_ref = .{ .meta = meta, .name = next_state_name } });
        const rec_call = try self.create(ast.Expr, .{
            .call = .{ .meta = meta, .callee = try self.create(ast.Expr, .{ .var_ref = .{ .meta = meta, .name = helper_name } }), .args = try self.allocSlice(*const ast.Expr, &.{next_state_ref}) },
        });

        // Body: [body(x) | __for_N(__next_state)]
        const body_d = try self.desugarExpr(fe.body);
        var cons_expr = try self.create(ast.Expr, .{
            .list_cons_expr = .{ .meta = meta, .head = body_d, .tail = rec_call },
        });

        // Filter
        if (fe.filter) |filter| {
            const fd = try self.desugarExpr(filter);
            cons_expr = try self.create(ast.Expr, .{
                .case_expr = .{ .meta = meta, .scrutinee = fd, .clauses = try self.allocSlice(ast.CaseClause, &.{
                    .{ .meta = meta, .pattern = try self.create(ast.Pattern, .{ .literal = .{ .bool_lit = .{ .meta = meta, .value = true } } }), .type_annotation = null, .guard = null, .body = try self.allocSlice(ast.Stmt, &.{.{ .expr = cons_expr }}) },
                    .{ .meta = meta, .pattern = try self.create(ast.Pattern, .{ .literal = .{ .bool_lit = .{ .meta = meta, .value = false } } }), .type_annotation = null, .guard = null, .body = try self.allocSlice(ast.Stmt, &.{.{ .expr = rec_call }}) },
                }) },
            });
        }

        // Tuple pattern: {:done, _, _} -> []
        const done_atom = try self.create(ast.Pattern, .{ .literal = .{ .atom = .{ .meta = meta, .value = try self.interner.intern("done") } } });
        const wildcard1 = try self.create(ast.Pattern, .{ .wildcard = .{ .meta = meta } });
        const wildcard2 = try self.create(ast.Pattern, .{ .wildcard = .{ .meta = meta } });
        const done_pat = try self.create(ast.Pattern, .{
            .tuple = .{ .meta = meta, .elements = try self.allocSlice(*const ast.Pattern, &.{ done_atom, wildcard1, wildcard2 }) },
        });
        const empty_list = try self.create(ast.Expr, .{ .list = .{ .meta = meta, .elements = &.{} } });

        // Tuple pattern: {:cont, <user-pattern>, __next_state} -> [body | rec]
        // When no annotation is present, the user's pattern slots
        // directly into the second tuple element. With `:: T`, the slot
        // becomes an internal bind and the cont-arm body opens with a
        // type-asserted re-binding through the standard assignment
        // pipeline (see buildLoopBind).
        const cont_atom = try self.create(ast.Pattern, .{ .literal = .{ .atom = .{ .meta = meta, .value = try self.interner.intern("cont") } } });
        const loop_bind = try self.buildLoopBind(fe, meta);
        const val_bind = loop_bind.pattern;
        const next_bind = try self.create(ast.Pattern, .{ .bind = .{ .meta = meta, .name = next_state_name } });
        const cont_pat = try self.create(ast.Pattern, .{
            .tuple = .{ .meta = meta, .elements = try self.allocSlice(*const ast.Pattern, &.{ cont_atom, val_bind, next_bind }) },
        });

        // case Enumerable.next(state) { {:done, _, _} -> []; {:cont, x, next} -> [body | rec] }
        const case_expr = try self.create(ast.Expr, .{
            .case_expr = .{
                .meta = meta,
                .scrutinee = next_call,
                .clauses = try self.allocSlice(ast.CaseClause, &.{
                    .{ .meta = meta, .pattern = done_pat, .type_annotation = null, .guard = null, .body = try self.allocSlice(ast.Stmt, &.{.{ .expr = empty_list }}) },
                    .{ .meta = meta, .pattern = cont_pat, .type_annotation = null, .guard = null, .body = try self.loopArmBody(loop_bind.pre_body, cons_expr) },
                }),
            },
        });

        // Leave return type unannotated — the type checker propagates the
        // body's `[BodyType]` shape via inferred_signatures so the helper
        // matches whatever element type the comprehension body produces.
        const clause = ast.FunctionClause{
            .meta = meta,
            .params = try self.allocSlice(ast.Param, &.{
                .{ .meta = meta, .pattern = try self.create(ast.Pattern, .{ .bind = .{ .meta = meta, .name = state_name } }), .type_annotation = null },
            }),
            .return_type = null,
            .refinement = null,
            .body = try self.allocSlice(ast.Stmt, &.{.{ .expr = case_expr }}),
        };

        const func_decl = try self.create(ast.FunctionDecl, .{
            .meta = meta,
            .name = helper_name,
            .clauses = try self.allocSlice(ast.FunctionClause, &.{clause}),
            .visibility = .private,
        });
        try self.pending_helpers.append(self.allocator, .{ .priv_function = func_decl });

        // Call: __for_N(iterable)
        const iterable = try self.desugarExpr(fe.iterable);
        return try self.create(ast.Expr, .{
            .call = .{ .meta = fe.meta, .callee = try self.create(ast.Expr, .{ .var_ref = .{ .meta = meta, .name = helper_name } }), .args = try self.allocSlice(*const ast.Expr, &.{iterable}) },
        });
    }

    // ============================================================
    // Import resolution (Elixir-style)
    //
    // Resolves bare function calls against the current struct's
    // imports. If `name/arity` is found in an imported struct
    // (including auto-imported Kernel), returns the source struct
    // name so the call can be rewritten as a qualified call.
    // ============================================================

    fn resolveImportedStruct(self: *const Desugarer, name: ast.StringId, arity: u32) ?ast.StructName {
        const graph = self.graph orelse return null;
        const mod_scope_id = self.current_struct_scope orelse return null;
        const scope = graph.getScope(mod_scope_id);

        // Check if the function is defined locally in this struct — if so,
        // don't rewrite (local definitions shadow imports).
        const key = scope_mod.FamilyKey{ .name = name, .arity = arity };
        if (scope.function_families.get(key) != null) return null;

        // Check imports (includes auto-imported Kernel)
        for (scope.imports.items) |imp| {
            if (graph.findStructScope(imp.source_struct)) |imp_scope_id| {
                const imp_scope = graph.getScope(imp_scope_id);
                if (imp_scope.function_families.get(key) != null) {
                    if (graph.passesImportFilter(imp.filter, key)) {
                        return imp.source_struct;
                    }
                }
            }
        }
        return null;
    }

    // ============================================================
    // Allocation helpers
    // ============================================================

    fn create(self: *Desugarer, comptime T: type, value: T) !*const T {
        const ptr = try self.allocator.create(T);
        ptr.* = value;
        return ptr;
    }

    fn allocSlice(self: *Desugarer, comptime T: type, items: []const T) ![]const T {
        const slice = try self.allocator.alloc(T, items.len);
        @memcpy(slice, items);
        return slice;
    }
};

// ============================================================
// Tests
// ============================================================

const Parser = @import("parser.zig").Parser;

test "pipe is desugared during macro expansion, not desugar" {
    // Pipe desugaring now happens in the macro engine (Phase 4).
    // The desugar pass just passes pipe nodes through.
    const source =
        \\pub struct Test {
        \\  pub fn foo(x) {
        \\    x |> bar(1)
        \\  }
        \\}
    ;

    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var parser = Parser.init(alloc, source);
    defer parser.deinit();
    const program = try parser.parseProgram();

    var desugarer = Desugarer.init(alloc, parser.interner, null);
    const desugared = try desugarer.desugarProgram(&program);

    // Pipe should still be a pipe (desugar doesn't transform it anymore)
    const func = desugared.structs[0].items[0].function;
    const body = func.clauses[0].body.?;
    try std.testing.expectEqual(@as(usize, 1), body.len);
    try std.testing.expect(body[0].expr.* == .pipe);
}

test "desugar no-op on simple expressions" {
    const source =
        \\pub struct Test {
        \\  pub fn add(x :: i64, y :: i64) -> i64 {
        \\    x + y
        \\  }
        \\}
    ;

    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var parser = Parser.init(alloc, source);
    defer parser.deinit();
    const program = try parser.parseProgram();

    var desugarer = Desugarer.init(alloc, parser.interner, null);
    const desugared = try desugarer.desugarProgram(&program);

    try std.testing.expectEqual(@as(usize, 1), desugared.structs.len);
    const func = desugared.structs[0].items[0].function;
    const body = func.clauses[0].body.?;
    try std.testing.expect(body[0].expr.* == .binary_op);
}

test "for inside macro body is not lifted into __for_N helper" {
    // Regression: a `for` comprehension inside a macro body was being
    // lifted out into a `__for_N` private function whose body still
    // referenced compile-time intrinsics (`elem`, `list_at`,
    // etc.). The type checker would then fail to find those names and
    // emit spurious "I cannot find a function named ..." warnings.
    // Macro bodies are evaluated by the macro engine, which handles
    // `for` directly via `forComprehensionIntrinsic`, so the lift is
    // both unnecessary and harmful.
    const source =
        \\pub struct Test {
        \\  pub macro do_thing(body :: Expr) -> Expr {
        \\    _stmts = elem(body, 2)
        \\    _xs = for _s <- _stmts, elem(_s, 0) == :setup { _s }
        \\    quote { unquote_splicing(_xs) }
        \\  }
        \\}
    ;

    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var parser = Parser.init(alloc, source);
    defer parser.deinit();
    const program = try parser.parseProgram();

    var desugarer = Desugarer.init(alloc, parser.interner, null);
    const desugared = try desugarer.desugarProgram(&program);

    // No item should be a generated `__for_N` helper. The single item
    // in the struct must be the macro itself.
    const items = desugared.structs[0].items;
    try std.testing.expectEqual(@as(usize, 1), items.len);
    try std.testing.expect(items[0] == .macro);

    // The for expression should remain as a `for_expr` node inside the
    // macro body's let-binding right-hand side, not be replaced by a
    // call to a generated helper.
    const macro_body = items[0].macro.clauses[0].body.?;
    // Body shape: [_stmts = elem(...), _xs = for ..., quote { ... }]
    try std.testing.expect(macro_body.len >= 2);
    const xs_assign = macro_body[1].assignment;
    try std.testing.expect(xs_assign.value.* == .for_expr);
}

test "for outside macro body is still lifted into __for_N helper" {
    // Counterpart to the previous test: a regular function still has
    // its `for` comprehension lifted, since the runtime needs an actual
    // helper to drive iteration. Without this, the macro-body skip
    // would over-fire and break runtime `for`.
    const source =
        \\pub struct Test {
        \\  pub fn run(xs :: List(i64)) -> List(i64) {
        \\    for x <- xs { x + 1 }
        \\  }
        \\}
    ;

    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var parser = Parser.init(alloc, source);
    defer parser.deinit();
    const program = try parser.parseProgram();

    var desugarer = Desugarer.init(alloc, parser.interner, null);
    const desugared = try desugarer.desugarProgram(&program);

    // The struct must contain the original `run` function plus at
    // least one synthesised `__for_N` private helper.
    const items = desugared.structs[0].items;
    try std.testing.expect(items.len >= 2);

    var found_helper = false;
    for (items) |item| {
        if (item == .priv_function) {
            const name = parser.interner.get(item.priv_function.name);
            if (std.mem.startsWith(u8, name, "__for_")) {
                found_helper = true;
                break;
            }
        }
    }
    try std.testing.expect(found_helper);
}

test "struct-level expressions synthesize public run function during desugar" {
    const source =
        \\pub struct Test {
        \\  marker()
        \\}
    ;

    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var parser = Parser.init(alloc, source);
    defer parser.deinit();
    const program = try parser.parseProgram();

    var desugarer = Desugarer.init(alloc, parser.interner, null);
    const desugared = try desugarer.desugarProgram(&program);

    const run_name = parser.interner.lookupExisting("run").?;
    const string_name = parser.interner.lookupExisting("String").?;
    var found_run = false;
    for (desugared.structs[0].items) |item| {
        if (item == .function and item.function.name == run_name) {
            found_run = true;
            try std.testing.expectEqual(ast.FunctionDecl.Visibility.public, item.function.visibility);
            try std.testing.expectEqual(@as(usize, 1), item.function.clauses.len);
            const clause = item.function.clauses[0];
            try std.testing.expectEqual(@as(usize, 0), clause.params.len);
            try std.testing.expect(clause.return_type.?.* == .name);
            try std.testing.expectEqual(string_name, clause.return_type.?.name.name);
            try std.testing.expectEqual(@as(usize, 1), clause.body.?.len);
            try std.testing.expect(clause.body.?[0].expr.* == .call);
        }
    }
    try std.testing.expect(found_run);
}

test "struct-level expressions do not duplicate existing run function" {
    const source =
        \\pub struct Test {
        \\  marker()
        \\
        \\  pub fn run() -> String {
        \\    "existing"
        \\  }
        \\}
    ;

    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    var parser = Parser.init(alloc, source);
    defer parser.deinit();
    const program = try parser.parseProgram();

    var desugarer = Desugarer.init(alloc, parser.interner, null);
    const desugared = try desugarer.desugarProgram(&program);

    const run_name = parser.interner.lookupExisting("run").?;
    var run_count: usize = 0;
    for (desugared.structs[0].items) |item| {
        if (item == .function and item.function.name == run_name) {
            run_count += 1;
        }
    }
    try std.testing.expectEqual(@as(usize, 1), run_count);
}
